version: '3'
services:
  posts-mvp-backend:
    container_name: posts-mvp-backend
    build:
      context: .
    expose:
      - ${PORT}
    working_dir: /app
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:3000
      - 9229:9229
    depends_on:
      - mysql
    links:
      - mysql
    env_file:
      - .env
    environment:
      - PORT=3000
      - MYSQL_CONNECTION_HOST=mysql
      - DATABASE_TYPE=mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_CONNECTION_DATABASE:-posts_mvp}
      - MYSQL_USER=${MYSQL_CONNECTION_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_CONNECTION_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}
    ports:
      - 3306:3306
